name: 'Base Release Setup'
description: 'Setup environment for Release'
# This action is used to set up the environment for a release.
# It is a reusable actions because it allows us to test the release process in the
# `build-and-check.yml` workflow.

runs:
  using: 'composite'
  steps:
    - name: Fetch tags
      shell: bash
      # Workaround for https://github.com/actions/checkout/issues/1471
      # See: https://github.com/actions/checkout/issues/1471#issuecomment-1755560284
      run: git fetch --prune --unshallow --tags
    - name: set up JDK 8
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        # Disable cache so that release is more hermetic
        cache-disabled: true
