name: Download and submit dependency graph

on:
  workflow_run:
    workflows: ['Build and check']
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Download and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          dependency-graph: download-and-submit # Download saved dependency-graph and submit
